version: '3'
services:
  nginx:
    build: ./nginx
    depends_on:
      - backend
    ports:
      - 80:80

  redis:
    image: redis
    ports:
      - 6379:6379
  
  frontend:
    build: 
      context: ./frontend
  
  
  backend:
    build: 
      context: ./backend
    ports:
      - 3000:3000
  

